export const ACCOUNT_SIGNUP_BEGIN = 'ACCOUNT_SIGNUP_BEGIN';
export const ACCOUNT_SIGNUP_SUCCESS = 'ACCOUNT_SIGNUP_SUCCESS';
export const ACCOUNT_SIGNUP_FAILURE = 'ACCOUNT_SIGNUP_FAILURE';

export const ACCOUNT_SIGNIN_BEGIN = 'ACCOUNT_SIGNIN_BEGIN';
export const ACCOUNT_SIGNIN_SUCCESS = 'ACCOUNT_SIGNIN_SUCCESS';
export const ACCOUNT_SIGNIN_FAILURE = 'ACCOUNT_SIGNIN_FAILURE';

export const ACCOUNT_LOGOUT_BEGIN = 'ACCOUNT_LOGOUT_BEGIN';
export const ACCOUNT_LOGOUT_SUCCESS = 'ACCOUNT_LOGOUT_SUCCESS';
export const ACCOUNT_LOGOUT_FAILURE = 'ACCOUNT_LOGOUT_FAILURE';

export const ACCOUNT_AUTHENTICATED_BEGIN = 'ACCOUNT_AUTHENTICATED_BEGIN';
export const ACCOUNT_AUTHENTICATED_SUCCESS = 'ACCOUNT_AUTHENTICATED_SUCCESS';
export const ACCOUNT_AUTHENTICATED_FAILURE = 'ACCOUNT_AUTHENTICATED_FAILURE';

export const ACCOUNT_INFO_FETCH_BEGIN = 'ACCOUNT_INFO_FETCH_BEGIN';
export const ACCOUNT_INFO_FETCH_SUCCESS = 'ACCOUNT_INFO_FETCH_SUCCESS';
export const ACCOUNT_INFO_FETCH_FAILURE = 'ACCOUNT_INFO_FETCH_FAILURE';