export const ACCOUNT_DRAGON_FETCH_BEGIN = 'ACCOUNT_DRAGON_FETCH_BEGIN';
export const ACCOUNT_DRAGON_FETCH_SUCCESS = 'ACCOUNT_DRAGON_FETCH_SUCCESS';
export const ACCOUNT_DRAGON_FETCH_FAILURE = 'ACCOUNT_DRAGON_FETCH_FAILURE';