export const ACCOUNT_INFO_FETCH_BEGIN = 'ACCOUNT_INFO_FETCH_BEGIN';
export const ACCOUNT_INFO_FETCH_SUCCESS = 'ACCOUNT_INFO_FETCH_SUCCESS';
export const ACCOUNT_INFO_FETCH_FAILURE = 'ACCOUNT_INFO_FETCH_FAILURE';