export const GENERATION_FETCH_BEGIN = 'GENERATION_FETCH_BEGIN';
export const GENERATION_FETCH_SUCCESS = 'GENERATION_FETCH_SUCCESS';
export const GENERATION_FETCH_FAILURE = 'GENERATION_FETCH_FAILURE';
