export const MATE_DRAGON_BEGIN = 'MATE_DRAGON_BEGIN';
export const MATE_DRAGON_SUCCESS = 'MATE_DRAGON_SUCCESS';
export const MATE_DRAGON_FAILURE = 'MATE_DRAGON_FAILURE';

export const SELECT_MATRON_DRAGON = 'SELECT_MATRON_DRAGON';