export const PUBLIC_DRAGON_FETCH_BEGIN = 'PUBLIC_DRAGON_FETCH_BEGIN';
export const PUBLIC_DRAGON_FETCH_SUCCESS = 'PUBLIC_DRAGON_FETCH_SUCCESS';
export const PUBLIC_DRAGON_FETCH_FAILURE = 'PUBLIC_DRAGON_FETCH_FAILURE';